name: Terraform Validate
on: [push, pull_request]

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        run: terraform -chdir=terraform/environments/dev fmt -check
      - name: Terraform validate
        run: terraform -chdir=terraform/environments/dev init -input=false && terraform -chdir=terraform/environments/dev validate
